name: stellar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  firebase_core: 2.24.2
  firebase_auth: 4.16.0
  google_sign_in: 6.2.1
  percent_indicator: 4.2.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          style: italic
          weight: 900
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          style: italic
          weight: 100
    - family: sf-pro-display
      fonts:
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYBLACKITALIC.OTF
          style: italic
          weight: 900
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYHEAVYITALIC.OTF
          style: italic
          weight: 800
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYBOLD.OTF
          weight: 700
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYSEMIBOLDITALIC.OTF
          style: italic
          weight: 600
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYLIGHTITALIC.OTF
          style: italic
          weight: 300
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYTHINITALIC.OTF
          style: italic
          weight: 200
        - asset: assets/fonts/sf_pro_display/SFPRODISPLAYULTRALIGHTITALIC.OTF
          style: italic
          weight: 100
  uses-material-design: true
