// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    databaseURL:
        'https://kreasi-anak-seni-default-rtdb.asia-southeast1.firebasedatabase.app/',
    apiKey: 'AIzaSyB-Ek2KJDiZmuB2dJyp3vARg5wX8MecFyc',
    appId: '1:144495025008:android:58b583ad474e5c2fcd4db5',
    messagingSenderId: '144495025008',
    projectId: 'kreasi-anak-seni',
    storageBucket: 'kreasi-anak-seni.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    databaseURL:
        'https://kreasi-anak-seni-default-rtdb.asia-southeast1.firebasedatabase.app/',
    apiKey: 'AIzaSyBZPdMKIYZYKDbbGuKbBEATe-_oBJT2zcg',
    appId: '1:144495025008:ios:7b42c31c4e9b232acd4db5',
    messagingSenderId: '144495025008',
    projectId: 'kreasi-anak-seni',
    storageBucket: 'kreasi-anak-seni.appspot.com',
    iosBundleId: 'com.enigma.stellar',
  );
}
